language: rust
os:
  - linux
env:
  global:
    - RUST_BACKTRACE=1
  matrix:
    - WASM=0
rust:
  - stable
  - nightly
matrix:
  include:
    - rust: stable
      env: WASM=1
      install:
        - rustup target add wasm32-unknown-unknown
        - cargo install -f cargo-web
      script:
        - cargo web check --features stdweb
    - rust: stable
      env: WASM=2
      install:
        - rustup target add wasm32-unknown-unknown
      script:
        - cargo check --target wasm32-unknown-unknown --features web_sys
  allow_failures:
    - rust: nightly
  fast_finish: true
